### ISSUE TITLE
Meetings not showing after creating

### ISSUE THREAD

**Issue by anushaharish538** [nordeck/matrix-meetings#174]
Hi,
I have installed https://github.com/nordeck/matrix-meetings/tree/main/matrix-meetings-widget. I used nginx reverse proxy  for http://localhost:3000. Its working fine. I have created widget and i'm able to schedule meetings but its not showing on calendar.

**Comment by nurjinjafar** [comment]
please make sure to follow the setup mentioned in the Repo!

and due to discussions on a [thread](https://matrix.to/#/!lIoibmoNDpIppeGzRd:matrix.org/$dA5lm4pn7oIcV2GpCol3BSc4YzXZJOFcHiLVnEpUVaw?via=matrix.org&via=dataport.modular.im&via=ergaster.org) this issue will be closed!

if you still might have this issue please reach out to us!
